name: CHYHSE
favicon: null
layout_spectrum: 0.73657
typography_spectrum: 0.14483
title: CHYHSE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8febfc'
    - '#24beff'
    - '#00dbff'
    - '#00fcff'
    - '#060d0f'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
