name: ChynaHouse
favicon: null
layout_spectrum: 0.2308
typography_spectrum: 0.27623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b20'
    - '#ec1219'
    - '#941012'
    - '#bf1016'
    - '#671217'
  brandStrength: 0.875
  lightness: 0.07724147895351052
  saturation: 0.8948667112272233
  rhythmicContrast: 0.19712288142181933
purpose: []
