name: CHYHSE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22872
title: CHYHSE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d4d4d4'
    - '#676767'
    - '#aaa8a9'
    - '#454243'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
