name: ChynaHouse
favicon: null
layout_spectrum: 0.2308
typography_spectrum: 0.27623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9e8e6'
    - '#f4f4f4'
    - '#f8f8f8'
    - '#efeeec'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
