name: CHYHSE
favicon: null
layout_spectrum: 0.24496
typography_spectrum: 0.14483
title: CHYHSE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#bdb585'
    - '#686868'
    - '#8e8873'
    - '#37352a'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
