name: CHYHSE
favicon: null
layout_spectrum: 0.2308
typography_spectrum: 0.12598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bdb585'
    - '#676767'
    - '#3a3433'
    - '#8f897e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.19712288142181933
purpose: []
